Adds oCam publisher package
UV-Lab/autoRCcar_indoor pull request #1
Opened 2023-08-19 03:37 UTC by yeonjokim

oCam 퍼블리셔 패키지를 추가합니다.

2023-08-19 05:25 UTC, gspark87 commented
사전 설치 패키지 README 남겨주세요

2023-08-19 05:28 UTC, dlfksj submitted a review, later dismissed

2023-08-19 05:28 UTC, gspark87 approved these changes

2023-08-19 05:30 UTC, gspark87 reviewed
취소

2023-08-19 05:30 UTC, gspark87 requested changes
취소

2023-08-20 07:17 UTC, luke7637 approved these changes

2023-08-20 07:18 UTC, yeonjokim commented
> 사전 설치 패키지 README 남겨주세요

@gspark87 @dlfksj @luke7637  @lmkknjjb 
추가했습니다!

<img width="983" alt="image" src="https://github.com/UV-Lab/autoRCcar_indoor/assets/25603375/bcb06eb6-1178-4751-9acf-7fae7c2836fd">

위에거 누르면 추가된 커밋에 대한 변경사항만 볼 수도 있습니다.

<img width="661" alt="image" src="https://github.com/UV-Lab/autoRCcar_indoor/assets/25603375/948ac0d9-9fb9-4fb3-9d89-d36eb07acfde">
File changed로 가서 "changes from ~~" 를 누르면 원하는 커밋만 표시할 수 있습니다.

2023-08-26 02:54 UTC, dlfksj approved these changes

2023-08-26 03:16 UTC, gspark87 approved these changes

2023-08-26 03:17 UTC, merged